/**
 * External tokenizer for space-sensitive `<` handling.
 *
 * In DepJS:
 * - `f<T>` (no space before <) means type arguments
 * - `f < T` (space before <) means comparison
 */

import { ExternalTokenizer } from "@lezer/lr";
// These will be generated by lezer-generator when the grammar builds
// For now, use placeholder values
const ltType = 1;
const ltCompare = 2;

// Character codes
const LT = 60; // <
const SPACE = 32;
const TAB = 9;
const NEWLINE = 10;
const CR = 13;

function isWhitespace(ch: number): boolean {
  return ch === SPACE || ch === TAB || ch === NEWLINE || ch === CR;
}

/**
 * External tokenizer that distinguishes between:
 * - ltType: < used for type arguments (no preceding whitespace)
 * - ltCompare: < used for comparison (preceded by whitespace)
 */
export const spaceTokens = new ExternalTokenizer((input) => {
  // Only handle <
  if (input.next !== LT) return;

  // Look back to check if there was whitespace before the <
  // input.peek(-1) gives us the character before current position
  // A negative return value or whitespace means this is a comparison
  const prevChar = input.peek(-1);
  const hadWhitespaceBefore = prevChar < 0 || isWhitespace(prevChar);

  input.advance();

  if (hadWhitespaceBefore) {
    // Space before < means comparison: `a < b`
    input.acceptToken(ltCompare);
  } else {
    // No space means type argument: `Array<Int>`
    input.acceptToken(ltType);
  }
});
